### ISSUE TITLE
Linkjes naar websites als buttons

### ISSUE THREAD

**Issue by th0mk** [Kefkef123/KentekenBot#6]
voorbeeld van zo'n soort button bij een andere coole bot:
![image](https://user-images.githubusercontent.com/9088316/169152068-2dd1a33a-8748-4739-9be1-3869569ce4eb.png)

- button naar kentekencheck voor auto
- button naar Finnik voor auto (handig voor kenteken historie en een paar andere stats)

**Comment by peters97** [comment]
Closed in #16
